# http://localhost:3000 で実行する場合
GOOGLE_APPLICATION_ID = "ABQIAAAAG1aAUyebKcmVH8kST6rXphTJQa0g3IQ9GZqIMmInSLzwtGDKaBQTo1Iom0Lb2v4tsvWzB-5g_Tr-yw"
# http://localhost で実行する場合
# GOOGLE_APPLICATION_ID = "ABQIAAAAnfs7bKE82qgb3Zc2YyS-oBT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3VcA"
